spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_db
    username: root
    password: root
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: order-group-1
    topics:
      order:
        name: orders
        partitions: 1
        replicas: 1
